### ISSUE TITLE
Preprocessing step + tokenization: managed or to do before submitting text?

### ISSUE THREAD

**Issue by nicolamassarenti** [MartinoMensio/it_vectors_wiki_spacy#3]
Hi Martino,

I've read that you created this spacy model starting from blank italian nlp + word vectors. Does your spacy wrapper already manage the preprocessing and tokenization? I mean, when submitting a text to spacy

```
model = spacy.load('it_vectors_wiki_lg')
result = model(text)
```

Is your model already able to execute the proper preprocessing and tokenization or  _text_ has to be a preprocessed and tokenized string?

I was wondering because I read from this [url (section Tokenization)](https://spacy.io/usage/spacy-101) that in general Spacy  manges preprocessing and tokenization already. Since you created a custom model, does the tokenization (and preprocessing) work as good as with other spacy italian models?

**Comment by MartinoMensio** [comment]
Hi Nicola,
The model is based on the Italian default pipeline as you can see at line 17 [`nlp = spacy.blank('it')`](https://github.com/MartinoMensio/it_vectors_wiki_spacy/blob/master/spacy_vectors.py#L17). This means that the pipeline is the most basic, and only has a tokenizer component (preprocessing and tokenization that you mentioned).
If you take a look at the top figure here https://spacy.io/usage/processing-pipelines, this means that only the red block exists, no tagger, parser or ner component exists. This means that if you try to do sentence-splitting (which requires a [sentencizer](https://spacy.io/api/sentencizer) or a dependency parser), you will receive an error:

```python
doc = nlp('Ciao! Vediamo che fa questo modello')
list(doc.sents)

--> ValueError: [E030] Sentence boundaries unset. You can add the 'sentencizer' component to the pipeline with: nlp.add_pipe(nlp.create_pipe('sentencizer')) Alternatively, add the dependency parser, or set sentence boundaries by setting doc[i].is_sent_start.
```

If you only need baser tokenization and preprocessing, the model should work as good as other Italian models.

If you need other features (e.g., tagger, parser, ner), take a look at the [italian models](https://spacy.io/models/it) which I see now also provide word embeddings for Italian in the `md` and `lg` variant.

**Comment by nicolamassarenti** [comment]
Great! 

Thanks for the answer.

Best,
Nicola
